name: external_storage_manager
description: Example Flutter app for managing files on external storage devices
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  file_picker: ^5.2.6

flutter:
  uses-material-design: true
